services:
  backend:
    build: ./backend
    ports:
      - "8084:8000"
    volumes:
      - ./backend:/app
    command: python manage.py runserver 0.0.0.0:8084

  frontend:
    build: ./frontend
    ports:
      - "3034:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start